server:
  port: 8080
  contextPath: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/culturelog
    username: culturelog
    password: culturelog
    schema: culturelog
  jpa:
    hibernate:
#    avoid actions on db via hibernate, will be done via liquibase
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${spring.datasource.schema}
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#        hbm2ddl:
#          auto: create

liquibase:
  change-log: classpath:db/liquibase/master.yml
#  defaultSchema: where liquibase tables are, needed to create schema culturelog
  defaultSchema: public
